# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from canonical_multipass_mcp import multipass_pb2 as canonical__multipass__mcp_dot_multipass__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in canonical_multipass_mcp/multipass_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RpcStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.create = channel.stream_stream(
                '/multipass.Rpc/create',
                request_serializer=canonical__multipass__mcp_dot_multipass__pb2.LaunchRequest.SerializeToString,
                response_deserializer=canonical__multipass__mcp_dot_multipass__pb2.LaunchReply.FromString,
                _registered_method=True)
        self.launch = channel.stream_stream(
                '/multipass.Rpc/launch',
                request_serializer=canonical__multipass__mcp_dot_multipass__pb2.LaunchRequest.SerializeToString,
                response_deserializer=canonical__multipass__mcp_dot_multipass__pb2.LaunchReply.FromString,
                _registered_method=True)
        self.purge = channel.stream_stream(
                '/multipass.Rpc/purge',
                request_serializer=canonical__multipass__mcp_dot_multipass__pb2.PurgeRequest.SerializeToString,
                response_deserializer=canonical__multipass__mcp_dot_multipass__pb2.PurgeReply.FromString,
                _registered_method=True)
        self.find = channel.stream_stream(
                '/multipass.Rpc/find',
                request_serializer=canonical__multipass__mcp_dot_multipass__pb2.FindRequest.SerializeToString,
                response_deserializer=canonical__multipass__mcp_dot_multipass__pb2.FindReply.FromString,
                _registered_method=True)
        self.info = channel.stream_stream(
                '/multipass.Rpc/info',
                request_serializer=canonical__multipass__mcp_dot_multipass__pb2.InfoRequest.SerializeToString,
                response_deserializer=canonical__multipass__mcp_dot_multipass__pb2.InfoReply.FromString,
                _registered_method=True)
        self.list = channel.stream_stream(
                '/multipass.Rpc/list',
                request_serializer=canonical__multipass__mcp_dot_multipass__pb2.ListRequest.SerializeToString,
                response_deserializer=canonical__multipass__mcp_dot_multipass__pb2.ListReply.FromString,
                _registered_method=True)
        self.networks = channel.stream_stream(
                '/multipass.Rpc/networks',
                request_serializer=canonical__multipass__mcp_dot_multipass__pb2.NetworksRequest.SerializeToString,
                response_deserializer=canonical__multipass__mcp_dot_multipass__pb2.NetworksReply.FromString,
                _registered_method=True)
        self.mount = channel.stream_stream(
                '/multipass.Rpc/mount',
                request_serializer=canonical__multipass__mcp_dot_multipass__pb2.MountRequest.SerializeToString,
                response_deserializer=canonical__multipass__mcp_dot_multipass__pb2.MountReply.FromString,
                _registered_method=True)
        self.ping = channel.unary_unary(
                '/multipass.Rpc/ping',
                request_serializer=canonical__multipass__mcp_dot_multipass__pb2.PingRequest.SerializeToString,
                response_deserializer=canonical__multipass__mcp_dot_multipass__pb2.PingReply.FromString,
                _registered_method=True)
        self.recover = channel.stream_stream(
                '/multipass.Rpc/recover',
                request_serializer=canonical__multipass__mcp_dot_multipass__pb2.RecoverRequest.SerializeToString,
                response_deserializer=canonical__multipass__mcp_dot_multipass__pb2.RecoverReply.FromString,
                _registered_method=True)
        self.ssh_info = channel.stream_stream(
                '/multipass.Rpc/ssh_info',
                request_serializer=canonical__multipass__mcp_dot_multipass__pb2.SSHInfoRequest.SerializeToString,
                response_deserializer=canonical__multipass__mcp_dot_multipass__pb2.SSHInfoReply.FromString,
                _registered_method=True)
        self.start = channel.stream_stream(
                '/multipass.Rpc/start',
                request_serializer=canonical__multipass__mcp_dot_multipass__pb2.StartRequest.SerializeToString,
                response_deserializer=canonical__multipass__mcp_dot_multipass__pb2.StartReply.FromString,
                _registered_method=True)
        self.stop = channel.stream_stream(
                '/multipass.Rpc/stop',
                request_serializer=canonical__multipass__mcp_dot_multipass__pb2.StopRequest.SerializeToString,
                response_deserializer=canonical__multipass__mcp_dot_multipass__pb2.StopReply.FromString,
                _registered_method=True)
        self.suspend = channel.stream_stream(
                '/multipass.Rpc/suspend',
                request_serializer=canonical__multipass__mcp_dot_multipass__pb2.SuspendRequest.SerializeToString,
                response_deserializer=canonical__multipass__mcp_dot_multipass__pb2.SuspendReply.FromString,
                _registered_method=True)
        self.restart = channel.stream_stream(
                '/multipass.Rpc/restart',
                request_serializer=canonical__multipass__mcp_dot_multipass__pb2.RestartRequest.SerializeToString,
                response_deserializer=canonical__multipass__mcp_dot_multipass__pb2.RestartReply.FromString,
                _registered_method=True)
        self.delet = channel.stream_stream(
                '/multipass.Rpc/delet',
                request_serializer=canonical__multipass__mcp_dot_multipass__pb2.DeleteRequest.SerializeToString,
                response_deserializer=canonical__multipass__mcp_dot_multipass__pb2.DeleteReply.FromString,
                _registered_method=True)
        self.umount = channel.stream_stream(
                '/multipass.Rpc/umount',
                request_serializer=canonical__multipass__mcp_dot_multipass__pb2.UmountRequest.SerializeToString,
                response_deserializer=canonical__multipass__mcp_dot_multipass__pb2.UmountReply.FromString,
                _registered_method=True)
        self.version = channel.stream_stream(
                '/multipass.Rpc/version',
                request_serializer=canonical__multipass__mcp_dot_multipass__pb2.VersionRequest.SerializeToString,
                response_deserializer=canonical__multipass__mcp_dot_multipass__pb2.VersionReply.FromString,
                _registered_method=True)
        self.get = channel.stream_stream(
                '/multipass.Rpc/get',
                request_serializer=canonical__multipass__mcp_dot_multipass__pb2.GetRequest.SerializeToString,
                response_deserializer=canonical__multipass__mcp_dot_multipass__pb2.GetReply.FromString,
                _registered_method=True)
        self.set = channel.stream_stream(
                '/multipass.Rpc/set',
                request_serializer=canonical__multipass__mcp_dot_multipass__pb2.SetRequest.SerializeToString,
                response_deserializer=canonical__multipass__mcp_dot_multipass__pb2.SetReply.FromString,
                _registered_method=True)
        self.keys = channel.stream_stream(
                '/multipass.Rpc/keys',
                request_serializer=canonical__multipass__mcp_dot_multipass__pb2.KeysRequest.SerializeToString,
                response_deserializer=canonical__multipass__mcp_dot_multipass__pb2.KeysReply.FromString,
                _registered_method=True)
        self.authenticate = channel.stream_stream(
                '/multipass.Rpc/authenticate',
                request_serializer=canonical__multipass__mcp_dot_multipass__pb2.AuthenticateRequest.SerializeToString,
                response_deserializer=canonical__multipass__mcp_dot_multipass__pb2.AuthenticateReply.FromString,
                _registered_method=True)
        self.snapshot = channel.stream_stream(
                '/multipass.Rpc/snapshot',
                request_serializer=canonical__multipass__mcp_dot_multipass__pb2.SnapshotRequest.SerializeToString,
                response_deserializer=canonical__multipass__mcp_dot_multipass__pb2.SnapshotReply.FromString,
                _registered_method=True)
        self.restore = channel.stream_stream(
                '/multipass.Rpc/restore',
                request_serializer=canonical__multipass__mcp_dot_multipass__pb2.RestoreRequest.SerializeToString,
                response_deserializer=canonical__multipass__mcp_dot_multipass__pb2.RestoreReply.FromString,
                _registered_method=True)
        self.clone = channel.stream_stream(
                '/multipass.Rpc/clone',
                request_serializer=canonical__multipass__mcp_dot_multipass__pb2.CloneRequest.SerializeToString,
                response_deserializer=canonical__multipass__mcp_dot_multipass__pb2.CloneReply.FromString,
                _registered_method=True)
        self.daemon_info = channel.stream_stream(
                '/multipass.Rpc/daemon_info',
                request_serializer=canonical__multipass__mcp_dot_multipass__pb2.DaemonInfoRequest.SerializeToString,
                response_deserializer=canonical__multipass__mcp_dot_multipass__pb2.DaemonInfoReply.FromString,
                _registered_method=True)


class RpcServicer(object):
    """Missing associated documentation comment in .proto file."""

    def create(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def launch(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def purge(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def find(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def info(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def list(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def networks(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def mount(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def recover(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ssh_info(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def start(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def stop(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def suspend(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def restart(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delet(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def umount(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def version(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def set(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def keys(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def authenticate(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def snapshot(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def restore(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def clone(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def daemon_info(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RpcServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'create': grpc.stream_stream_rpc_method_handler(
                    servicer.create,
                    request_deserializer=canonical__multipass__mcp_dot_multipass__pb2.LaunchRequest.FromString,
                    response_serializer=canonical__multipass__mcp_dot_multipass__pb2.LaunchReply.SerializeToString,
            ),
            'launch': grpc.stream_stream_rpc_method_handler(
                    servicer.launch,
                    request_deserializer=canonical__multipass__mcp_dot_multipass__pb2.LaunchRequest.FromString,
                    response_serializer=canonical__multipass__mcp_dot_multipass__pb2.LaunchReply.SerializeToString,
            ),
            'purge': grpc.stream_stream_rpc_method_handler(
                    servicer.purge,
                    request_deserializer=canonical__multipass__mcp_dot_multipass__pb2.PurgeRequest.FromString,
                    response_serializer=canonical__multipass__mcp_dot_multipass__pb2.PurgeReply.SerializeToString,
            ),
            'find': grpc.stream_stream_rpc_method_handler(
                    servicer.find,
                    request_deserializer=canonical__multipass__mcp_dot_multipass__pb2.FindRequest.FromString,
                    response_serializer=canonical__multipass__mcp_dot_multipass__pb2.FindReply.SerializeToString,
            ),
            'info': grpc.stream_stream_rpc_method_handler(
                    servicer.info,
                    request_deserializer=canonical__multipass__mcp_dot_multipass__pb2.InfoRequest.FromString,
                    response_serializer=canonical__multipass__mcp_dot_multipass__pb2.InfoReply.SerializeToString,
            ),
            'list': grpc.stream_stream_rpc_method_handler(
                    servicer.list,
                    request_deserializer=canonical__multipass__mcp_dot_multipass__pb2.ListRequest.FromString,
                    response_serializer=canonical__multipass__mcp_dot_multipass__pb2.ListReply.SerializeToString,
            ),
            'networks': grpc.stream_stream_rpc_method_handler(
                    servicer.networks,
                    request_deserializer=canonical__multipass__mcp_dot_multipass__pb2.NetworksRequest.FromString,
                    response_serializer=canonical__multipass__mcp_dot_multipass__pb2.NetworksReply.SerializeToString,
            ),
            'mount': grpc.stream_stream_rpc_method_handler(
                    servicer.mount,
                    request_deserializer=canonical__multipass__mcp_dot_multipass__pb2.MountRequest.FromString,
                    response_serializer=canonical__multipass__mcp_dot_multipass__pb2.MountReply.SerializeToString,
            ),
            'ping': grpc.unary_unary_rpc_method_handler(
                    servicer.ping,
                    request_deserializer=canonical__multipass__mcp_dot_multipass__pb2.PingRequest.FromString,
                    response_serializer=canonical__multipass__mcp_dot_multipass__pb2.PingReply.SerializeToString,
            ),
            'recover': grpc.stream_stream_rpc_method_handler(
                    servicer.recover,
                    request_deserializer=canonical__multipass__mcp_dot_multipass__pb2.RecoverRequest.FromString,
                    response_serializer=canonical__multipass__mcp_dot_multipass__pb2.RecoverReply.SerializeToString,
            ),
            'ssh_info': grpc.stream_stream_rpc_method_handler(
                    servicer.ssh_info,
                    request_deserializer=canonical__multipass__mcp_dot_multipass__pb2.SSHInfoRequest.FromString,
                    response_serializer=canonical__multipass__mcp_dot_multipass__pb2.SSHInfoReply.SerializeToString,
            ),
            'start': grpc.stream_stream_rpc_method_handler(
                    servicer.start,
                    request_deserializer=canonical__multipass__mcp_dot_multipass__pb2.StartRequest.FromString,
                    response_serializer=canonical__multipass__mcp_dot_multipass__pb2.StartReply.SerializeToString,
            ),
            'stop': grpc.stream_stream_rpc_method_handler(
                    servicer.stop,
                    request_deserializer=canonical__multipass__mcp_dot_multipass__pb2.StopRequest.FromString,
                    response_serializer=canonical__multipass__mcp_dot_multipass__pb2.StopReply.SerializeToString,
            ),
            'suspend': grpc.stream_stream_rpc_method_handler(
                    servicer.suspend,
                    request_deserializer=canonical__multipass__mcp_dot_multipass__pb2.SuspendRequest.FromString,
                    response_serializer=canonical__multipass__mcp_dot_multipass__pb2.SuspendReply.SerializeToString,
            ),
            'restart': grpc.stream_stream_rpc_method_handler(
                    servicer.restart,
                    request_deserializer=canonical__multipass__mcp_dot_multipass__pb2.RestartRequest.FromString,
                    response_serializer=canonical__multipass__mcp_dot_multipass__pb2.RestartReply.SerializeToString,
            ),
            'delet': grpc.stream_stream_rpc_method_handler(
                    servicer.delet,
                    request_deserializer=canonical__multipass__mcp_dot_multipass__pb2.DeleteRequest.FromString,
                    response_serializer=canonical__multipass__mcp_dot_multipass__pb2.DeleteReply.SerializeToString,
            ),
            'umount': grpc.stream_stream_rpc_method_handler(
                    servicer.umount,
                    request_deserializer=canonical__multipass__mcp_dot_multipass__pb2.UmountRequest.FromString,
                    response_serializer=canonical__multipass__mcp_dot_multipass__pb2.UmountReply.SerializeToString,
            ),
            'version': grpc.stream_stream_rpc_method_handler(
                    servicer.version,
                    request_deserializer=canonical__multipass__mcp_dot_multipass__pb2.VersionRequest.FromString,
                    response_serializer=canonical__multipass__mcp_dot_multipass__pb2.VersionReply.SerializeToString,
            ),
            'get': grpc.stream_stream_rpc_method_handler(
                    servicer.get,
                    request_deserializer=canonical__multipass__mcp_dot_multipass__pb2.GetRequest.FromString,
                    response_serializer=canonical__multipass__mcp_dot_multipass__pb2.GetReply.SerializeToString,
            ),
            'set': grpc.stream_stream_rpc_method_handler(
                    servicer.set,
                    request_deserializer=canonical__multipass__mcp_dot_multipass__pb2.SetRequest.FromString,
                    response_serializer=canonical__multipass__mcp_dot_multipass__pb2.SetReply.SerializeToString,
            ),
            'keys': grpc.stream_stream_rpc_method_handler(
                    servicer.keys,
                    request_deserializer=canonical__multipass__mcp_dot_multipass__pb2.KeysRequest.FromString,
                    response_serializer=canonical__multipass__mcp_dot_multipass__pb2.KeysReply.SerializeToString,
            ),
            'authenticate': grpc.stream_stream_rpc_method_handler(
                    servicer.authenticate,
                    request_deserializer=canonical__multipass__mcp_dot_multipass__pb2.AuthenticateRequest.FromString,
                    response_serializer=canonical__multipass__mcp_dot_multipass__pb2.AuthenticateReply.SerializeToString,
            ),
            'snapshot': grpc.stream_stream_rpc_method_handler(
                    servicer.snapshot,
                    request_deserializer=canonical__multipass__mcp_dot_multipass__pb2.SnapshotRequest.FromString,
                    response_serializer=canonical__multipass__mcp_dot_multipass__pb2.SnapshotReply.SerializeToString,
            ),
            'restore': grpc.stream_stream_rpc_method_handler(
                    servicer.restore,
                    request_deserializer=canonical__multipass__mcp_dot_multipass__pb2.RestoreRequest.FromString,
                    response_serializer=canonical__multipass__mcp_dot_multipass__pb2.RestoreReply.SerializeToString,
            ),
            'clone': grpc.stream_stream_rpc_method_handler(
                    servicer.clone,
                    request_deserializer=canonical__multipass__mcp_dot_multipass__pb2.CloneRequest.FromString,
                    response_serializer=canonical__multipass__mcp_dot_multipass__pb2.CloneReply.SerializeToString,
            ),
            'daemon_info': grpc.stream_stream_rpc_method_handler(
                    servicer.daemon_info,
                    request_deserializer=canonical__multipass__mcp_dot_multipass__pb2.DaemonInfoRequest.FromString,
                    response_serializer=canonical__multipass__mcp_dot_multipass__pb2.DaemonInfoReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'multipass.Rpc', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('multipass.Rpc', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Rpc(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def create(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/multipass.Rpc/create',
            canonical__multipass__mcp_dot_multipass__pb2.LaunchRequest.SerializeToString,
            canonical__multipass__mcp_dot_multipass__pb2.LaunchReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def launch(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/multipass.Rpc/launch',
            canonical__multipass__mcp_dot_multipass__pb2.LaunchRequest.SerializeToString,
            canonical__multipass__mcp_dot_multipass__pb2.LaunchReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def purge(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/multipass.Rpc/purge',
            canonical__multipass__mcp_dot_multipass__pb2.PurgeRequest.SerializeToString,
            canonical__multipass__mcp_dot_multipass__pb2.PurgeReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def find(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/multipass.Rpc/find',
            canonical__multipass__mcp_dot_multipass__pb2.FindRequest.SerializeToString,
            canonical__multipass__mcp_dot_multipass__pb2.FindReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def info(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/multipass.Rpc/info',
            canonical__multipass__mcp_dot_multipass__pb2.InfoRequest.SerializeToString,
            canonical__multipass__mcp_dot_multipass__pb2.InfoReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def list(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/multipass.Rpc/list',
            canonical__multipass__mcp_dot_multipass__pb2.ListRequest.SerializeToString,
            canonical__multipass__mcp_dot_multipass__pb2.ListReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def networks(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/multipass.Rpc/networks',
            canonical__multipass__mcp_dot_multipass__pb2.NetworksRequest.SerializeToString,
            canonical__multipass__mcp_dot_multipass__pb2.NetworksReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def mount(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/multipass.Rpc/mount',
            canonical__multipass__mcp_dot_multipass__pb2.MountRequest.SerializeToString,
            canonical__multipass__mcp_dot_multipass__pb2.MountReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/multipass.Rpc/ping',
            canonical__multipass__mcp_dot_multipass__pb2.PingRequest.SerializeToString,
            canonical__multipass__mcp_dot_multipass__pb2.PingReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def recover(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/multipass.Rpc/recover',
            canonical__multipass__mcp_dot_multipass__pb2.RecoverRequest.SerializeToString,
            canonical__multipass__mcp_dot_multipass__pb2.RecoverReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ssh_info(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/multipass.Rpc/ssh_info',
            canonical__multipass__mcp_dot_multipass__pb2.SSHInfoRequest.SerializeToString,
            canonical__multipass__mcp_dot_multipass__pb2.SSHInfoReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def start(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/multipass.Rpc/start',
            canonical__multipass__mcp_dot_multipass__pb2.StartRequest.SerializeToString,
            canonical__multipass__mcp_dot_multipass__pb2.StartReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def stop(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/multipass.Rpc/stop',
            canonical__multipass__mcp_dot_multipass__pb2.StopRequest.SerializeToString,
            canonical__multipass__mcp_dot_multipass__pb2.StopReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def suspend(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/multipass.Rpc/suspend',
            canonical__multipass__mcp_dot_multipass__pb2.SuspendRequest.SerializeToString,
            canonical__multipass__mcp_dot_multipass__pb2.SuspendReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def restart(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/multipass.Rpc/restart',
            canonical__multipass__mcp_dot_multipass__pb2.RestartRequest.SerializeToString,
            canonical__multipass__mcp_dot_multipass__pb2.RestartReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def delet(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/multipass.Rpc/delet',
            canonical__multipass__mcp_dot_multipass__pb2.DeleteRequest.SerializeToString,
            canonical__multipass__mcp_dot_multipass__pb2.DeleteReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def umount(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/multipass.Rpc/umount',
            canonical__multipass__mcp_dot_multipass__pb2.UmountRequest.SerializeToString,
            canonical__multipass__mcp_dot_multipass__pb2.UmountReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def version(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/multipass.Rpc/version',
            canonical__multipass__mcp_dot_multipass__pb2.VersionRequest.SerializeToString,
            canonical__multipass__mcp_dot_multipass__pb2.VersionReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def get(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/multipass.Rpc/get',
            canonical__multipass__mcp_dot_multipass__pb2.GetRequest.SerializeToString,
            canonical__multipass__mcp_dot_multipass__pb2.GetReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def set(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/multipass.Rpc/set',
            canonical__multipass__mcp_dot_multipass__pb2.SetRequest.SerializeToString,
            canonical__multipass__mcp_dot_multipass__pb2.SetReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def keys(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/multipass.Rpc/keys',
            canonical__multipass__mcp_dot_multipass__pb2.KeysRequest.SerializeToString,
            canonical__multipass__mcp_dot_multipass__pb2.KeysReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def authenticate(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/multipass.Rpc/authenticate',
            canonical__multipass__mcp_dot_multipass__pb2.AuthenticateRequest.SerializeToString,
            canonical__multipass__mcp_dot_multipass__pb2.AuthenticateReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def snapshot(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/multipass.Rpc/snapshot',
            canonical__multipass__mcp_dot_multipass__pb2.SnapshotRequest.SerializeToString,
            canonical__multipass__mcp_dot_multipass__pb2.SnapshotReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def restore(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/multipass.Rpc/restore',
            canonical__multipass__mcp_dot_multipass__pb2.RestoreRequest.SerializeToString,
            canonical__multipass__mcp_dot_multipass__pb2.RestoreReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def clone(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/multipass.Rpc/clone',
            canonical__multipass__mcp_dot_multipass__pb2.CloneRequest.SerializeToString,
            canonical__multipass__mcp_dot_multipass__pb2.CloneReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def daemon_info(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/multipass.Rpc/daemon_info',
            canonical__multipass__mcp_dot_multipass__pb2.DaemonInfoRequest.SerializeToString,
            canonical__multipass__mcp_dot_multipass__pb2.DaemonInfoReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
